{
 "title": "Java Micrometer",
 "description": "Java metrics exposed with Micrometer",
 "tags": [
  "java",
  "micrometer"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "JVM Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Threads Peak",
   "type": "graph",
   "description": "The peak live thread count since the Java virtual machine started or peak was reset",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_peak_threads" }
   ]
  },
  {
   "title": "Live Daemon Threads",
   "type": "graph",
   "description": "The current number of live daemon threads",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_daemon_threads" }
   ]
  },
  {
   "title": "Live Total Threads",
   "type": "graph",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_live_threads" }
   ]
  },
  { "title": "JVM Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Buffer Count",
   "type": "graph",
   "description": "An estimate of the number of buffers in the pool",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_buffer_count_buffers", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Buffer Mem Used",
   "type": "graph",
   "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Buffer Capacity",
   "type": "graph",
   "description": "An estimate of the total capacity of the buffers in this pool",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Max Memory",
   "type": "graph",
   "description": "The maximum amount of memory in bytes that can be used for memory management",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_max_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "description": "The amount of used memory",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  {
   "title": "Committed Memory",
   "type": "graph",
   "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_committed_bytes", "legendFormat": "{{id}} ({{area}})" }
   ]
  },
  { "title": "JVM Garbage Collection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Max Data Size",
   "type": "graph",
   "description": "Max size of old generation memory pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_gc_max_data_size_bytes" }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "graph",
   "description": "Size of old generation memory pool after a full GC",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "jvm_gc_live_data_size_bytes" }
   ]
  },
  { "title": "Class Loader Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "description": "The number of classes that are currently loaded in the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_loaded_classes" }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "description": "The total number of classes unloaded since the Java virtual machine has started execution",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes_total"
    }
   ]
  }
 ]
}