apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: employee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: serrodcal/employees-quarkus-prometheus-jvm:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: postgresql://database:5432/quarkus_test
          resources:
            limits:
              memory: 1G
              cpu: 1000m
            requests:
              memory: 1G
              cpu: 1000m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: employee
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
