apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: nginx:1.17.10-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 1G
              cpu: 1000m
            requests:
              memory: 1G
              cpu: 1000m
          volumeMounts:
          - name: gateway-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          # statics folder: /usr/share/nginx/html
      volumes:
      - name: gateway-config
        configMap:
          name: gateway-cm
          items:
            - key: nginx.conf
              path: nginx.conf
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-cm
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;

        server {
          listen 8080;

          # Lazy load proxy_pass and do check only when request comes in
          set $employee_upstream "http://employee.default.svc.cluster.local:8080";
          set $department_upstream "http://department.default.svc.cluster.local:8080";
          set $hr_upstream "http://hr.default.svc.cluster.local:8080";
          set $grafana_upstream "http://grafana.default.svc.cluster.local:3000";
          set $jaeger_upstream "http://jaeger.default.svc.cluster.local:16686";
          set $kibana_upstream "http://kibana.default.svc.cluster.local:5601";
          set $prometheus_upstream "http://prometheus.default.svc.cluster.local:9090";

          # Need it for lazy load
          resolver kube-dns.kube-system.svc.cluster.local ipv6=off;

          location ~* ^/api/v1/employee/?(.*) {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'OPTIONS, GET, POST, PUT, DELETE';
            proxy_pass $employee_upstream;
          }

          location ~* ^/api/v1/department/?(.*) {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'OPTIONS, GET, POST, PUT, DELETE';
            proxy_pass $department_upstream;
          }

          location ~* ^/api/v1/hr/?(.*) {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'OPTIONS, GET, POST, PUT, DELETE';
            proxy_pass $hr_upstream;
          }

          # Expose swagger-ui
          location ~* ^/employee/(.*) {
            proxy_pass $employee_upstream;
          }

          # Expose swagger-ui
          location ~* ^/department/(.*) {
            proxy_pass $department_upstream;
          }

          # Expose swagger-ui
          location ~* ^/hr/(.*) {
            proxy_pass $hr_upstream;
          }

          location /grafana {
            proxy_pass $grafana_upstream;
          }

          location /jaeger {
            proxy_pass $jaeger_upstream;
          }

          location /kibana {
            proxy_pass $kibana_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
          }

          location /prometheus {
            proxy_pass $prometheus_upstream;
          }

        }

    }
